# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_row = QtWidgets.QHBoxLayout()
        self.input_row.setObjectName("input_row")
        self.value_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_label.sizePolicy().hasHeightForWidth())
        self.value_label.setSizePolicy(sizePolicy)
        self.value_label.setObjectName("value_label")
        self.input_row.addWidget(self.value_label)
        self.value_input = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_input.sizePolicy().hasHeightForWidth())
        self.value_input.setSizePolicy(sizePolicy)
        self.value_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.value_input.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.value_input.setMinimum(0.0)
        self.value_input.setMaximum(1000.0)
        self.value_input.setSingleStep(0.01)
        self.value_input.setObjectName("value_input")
        self.input_row.addWidget(self.value_input)
        self.from_currency_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_currency_label.sizePolicy().hasHeightForWidth())
        self.from_currency_label.setSizePolicy(sizePolicy)
        self.from_currency_label.setObjectName("from_currency_label")
        self.input_row.addWidget(self.from_currency_label)
        self.from_currency_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.from_currency_input.setMaxLength(3)
        self.from_currency_input.setObjectName("from_currency_input")
        self.input_row.addWidget(self.from_currency_input)
        self.to_currency_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_currency_label.sizePolicy().hasHeightForWidth())
        self.to_currency_label.setSizePolicy(sizePolicy)
        self.to_currency_label.setObjectName("to_currency_label")
        self.input_row.addWidget(self.to_currency_label)
        self.to_currency_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.to_currency_input.setObjectName("to_currency_input")
        self.input_row.addWidget(self.to_currency_input)
        self.convert_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convert_button.sizePolicy().hasHeightForWidth())
        self.convert_button.setSizePolicy(sizePolicy)
        self.convert_button.setObjectName("convert_button")
        self.input_row.addWidget(self.convert_button)
        self.live_data = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.live_data.sizePolicy().hasHeightForWidth())
        self.live_data.setSizePolicy(sizePolicy)
        self.live_data.setChecked(True)
        self.live_data.setObjectName("live_data")
        self.input_row.addWidget(self.live_data)
        self.verticalLayout.addLayout(self.input_row)
        self.result_display = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.result_display.setReadOnly(True)
        self.result_display.setObjectName("result_display")
        self.verticalLayout.addWidget(self.result_display)
        self.button_row = QtWidgets.QHBoxLayout()
        self.button_row.setObjectName("button_row")
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setObjectName("exit_button")
        self.button_row.addWidget(self.exit_button)
        self.reset_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setObjectName("reset_button")
        self.button_row.addWidget(self.reset_button)
        self.verticalLayout.addLayout(self.button_row)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Currency Converter"))
        self.value_label.setText(_translate("MainWindow", "Betrag:"))
        self.from_currency_label.setText(_translate("MainWindow", "Ausgangswährung:"))
        self.from_currency_input.setText(_translate("MainWindow", "EUR"))
        self.to_currency_label.setText(_translate("MainWindow", "Zielwährungen:"))
        self.to_currency_input.setText(_translate("MainWindow", "GBP,USD"))
        self.convert_button.setText(_translate("MainWindow", "Umrechnen"))
        self.live_data.setText(_translate("MainWindow", "Live-Daten"))
        self.exit_button.setText(_translate("MainWindow", "Schließen"))
        self.reset_button.setText(_translate("MainWindow", "Zurücksetzen"))

